env: local
port: 1324
apiTokenKey: secret
schedulerTokenKey: secret
callbackTokenKey: secret
appCorsDomain: "*"

# jwt auth
jwtAuth:
  jwtSecretKey: secret
  jwtRefreshSecretKey: secret
  jwtExpire: 3600


# postgres database local
mysql:
  maxOpenConnections: 4
  maxIdleConnections: 2
  master:
    host: localhost
    port: 3306
    database: management_auth_db
    username: root
    password: 
  slave:
    host: localhost
    port: 3306
    database: management_auth_db
    username: root
    password: 