env: local
port: 1324
apiTokenKey: secret
schedulerTokenKey: secret
callbackTokenKey: secret
appCorsDomain: "*"

# jwt auth
jwtAuth:
  jwtSecretKey: secret
  jwtRefreshSecretKey: refreshsecret
  jwtExpireTime: 2
  jwtRefreshExpireTime: 2
  jwtExpire: 72
# jwt expire in Hour

authClient:
  baseURL: http://localhost:1325
  retryCount: 0
  retryWaitTime: 3
  timeout: 60


# postgres database local
mysql:
  maxOpenConnections: 8
  maxIdleConnections: 4
  # master:
  #   host: localhost
  #   port: 3306
  #   database: management_auth_db
  #   username: root
  #   password: 
  # slave:
  #   host: localhost
  #   port: 3306
  #   database: management_auth_db
  #   username: root
  #   password: 

  master:
    host: 85.10.205.173
    port: 3306
    database: managementauthdb
    username: viantoauth
    password: Vianto00123
  slave:
    host: 85.10.205.173
    port: 3306
    database: managementauthdb
    username: viantoauth
    password: Vianto00123