env: local
port: 1325
apiTokenKey: secret
schedulerTokenKey: secret
callbackTokenKey: secret
appCorsDomain: "*"

# jwt auth
jwtAuth:
  jwtSecretKey: secret
  jwtRefreshSecretKey: refreshsecret
  jwtExpireTime: 2
  jwtRefreshExpireTime: 2
  jwtExpire: 72
# jwt expire in Hour

authClient:
  baseURL: http://localhost:1325
  retryCount: 0
  retryWaitTime: 3
  timeout: 60


# postgres database local
mysql:
  maxOpenConnections: 4
  maxIdleConnections: 2
  master:
    host: db4free.net
    port: 3306
    database: management_auth
    username: viantonugroho_db
    password: Vianto1125!@
  slave:
    host: db4free.net
    port: 3306
    database: management_auth
    username: viantonugroho_db
    password: Vianto1125!@