env: local
port: 1325
apiTokenKey: secret
schedulerTokenKey: secret
callbackTokenKey: secret
appCorsDomain: "*"

# jwt auth
jwtAuth:
  jwtSecretKey: secret
  jwtRefreshSecretKey: refreshsecret
  jwtExpireTime: 2
  jwtRefreshExpireTime: 2
  jwtExpire: 72
# jwt expire in Hour


# postgres database local
mysql:
  maxOpenConnections: 4
  maxIdleConnections: 2
  master:
    host: localhost
    port: 3306
    database: management_auth_db
    username: root
    password: 
  slave:
    host: localhost
    port: 3306
    database: management_auth_db
    username: root
    password: 